print("")
print("SELAMAT DATANG DI KANTOR PUSAT SOLO")
print("")
print(" |——————————————————————————|")
print("| •APA YANG INGIN ANDA BUAT• |")
print(" |——————————————————————————|")
print("")
print("[1] Membuat KTP")
print("")
print("[2] Membuat SIM")
print("")
membuat = int(input("Masukkan salah satu pilihan di atas :"))
if membuat ==1:
  print("")
  print("Jika anda ingin membuat KTP minimal usia anda 18 tahun maksimal 50 tahun")
  print("")
  umur = int(input("Barapa umur anda : "))
  if umur <=17:
    print("")
    print("Maaf anda tidak boleh membuat KTP")
    print("")
    print("TERIMA KASIH")
    print("")
  elif umur >=51:
    print("")
    print("Maaf anda tidak boleh membuat KTP")
    print("")
    print("TERIMA KASIH")
    print("")
  else:
    print("")
    print("Selamat anda boleh membuat KTP")
    print("")
    print("Untuk info lebih lanjut hubungi kami, WA:085601952198")
    print("")
    print("TERIMA KASIH")
    print("")
elif membuat ==2:
  print("")
  print("Jika anda ingin membuat SIM minimal anda harus berumur 18-50 tahun")
  print("Dan anda harus menguasai setidaknya  dasar-dasar berkendara")
  print("")
  dasar = int(input("Berapa umur anda : "))
  if dasar <=17:
    print("")
    print("Maaf anda belum cukup umur untuk membuat SIM")
    print("")
    print("TERIMA KASIH")
    print("")
  elif dasar >=51:
    print("")
    print("Maaf anda tidak boleh membuat SIM")
    print("")
    print("TERIMA KASIH")
    print("")
  else:
    print("")
    print("Selamat anda boleh membuat SIM")
    print("")
    print("Untuk info lebih lanjut hubungi no berikut")
    print("")
    print("WA:085601952198")
    print("")
else:
  print("")
  print("Maaf Keywoard yang anda masukkan salah!!!")
  print("")