print("")
print("Selamat datang di toko Jaya Abadi")
print("")
print("Menu Pilihan")
print("")
print("[1] Baju")
print("")
print("[2] Celana")
print("")
toko = int(input("Masukkan pilihan : "))
if toko ==1:
  print("")
  print("1 baju harganya Rp.70.000")
  print("")